### PR TITLE
Changed verify to use executeOnFiles()

### LINKED ISSUE #15: .eslintrc not resolving to nearest parent
I'm finding that when .eslintrc's are defined for specific directories and there is also a root .eslintrc, gulp-eslint is utilizing the root level.  I confirmed this by manually running eslint to confirm it is correctly leveraging the nearest parent to the javascript file.

### PR DESCRIPTION
**Pull request by delasteve**
This fixes #15 for me. I would love to hear if there is any problem with anyone else's configs.

### CODE REVIEW

**Comment by fdubost** [comment]
:+1:

**Comment by pedrosland** [comment]
I've not actually tried this but I suspect that it will only work for real files. What I mean is, if you want to lint a file that has been [renamed](https://github.com/hparra/gulp-rename) or [modified](https://github.com/AntouanK/gulp-wrapper) then I don't think this will work until it has been saved (`gulp.dest`).

Having said that, I'm not really sure why you'd really want to modify a file before linting as it'll just mess up your line numbers :).

It might be better though to use the contents of the Vinyl files since gulp has already read the contents of the files, why read them again?

**Comment by delasteve** [comment]
True. I actually used executeOnText in my replacement for this gulp plug-in. I planned on releasing it this weekend, but had a death in the family. I hope to get back to it next weekend since this maintainer looks like he may have given up.

**Comment by adametry** [comment]
As @pedrosland and @delasteve pointed out, the use of executeOnText is to lint the vinyl file's content (that originated from some file). This allows any number of gulp transformations to occur to the contents prior to linting (e.g., file concatenation).

I believe the intent of this PR is to ensure that .eslintignore and .eslintrc files are read from appropriate/relative directories. I can look into addressing this issue (or accept PR).

For linting a collection of files, the [eslint's CLI](http://eslint.org/docs/command-line-interface/) is better suited since gulp would only function as a glob tool. I can provide more detail if this is the case.

**Comment by adametry** [comment]
An update has been published that replicates the way executeOnFiles loads local .eslintrc and .eslintignore files while using the vinyl file's content. This update should achieve the goal of this PR.

I'm going to close this PR. If there are additional concerns, let's create a separate issue.

**Pull request closed without merging**
