### PR TITLE
Updated object-assign due to breaking bug

### PR DESCRIPTION
**Pull request by jhorwit2**
https://github.com/sindresorhus/object-assign/issues/15

### CODE REVIEW

**Comment by sindresorhus** [comment]
As said in the original thread, this isn't strictly needed as the offending version was pulled. 3.0.0 only brings a new feature, which is `Symbol` support.

**Comment by zdychacek** [comment]
+1

**Comment by mako-taco** [comment]
:+1: PLUS ONE +1

**Comment by adametry** [comment]
Might as well update dependencies.

Since the object-assign bug was addressed and there's no functional change to gulp-eslint, this gets a patch bump. v0.13.1 has been published.

Thanks for the PR!

**Pull request merged**
