### PR TITLE
update eslint to v0.11.0

### PR DESCRIPTION
**Pull request by jlandure**

### CODE REVIEW

**Comment by DrBenton** [comment]
:+1:

**Comment by gerrypower** [comment]
+1

**Comment by tetor** [comment]
LGTM

**Comment by gilbarbara** [comment]
Yes, please! 👊

**Comment by MethodGrab** [comment]
There's already #19 open for this, it's been open since 0.10 was released!

**Comment by mrak** [comment]
PR #19 fixes this issue for all eslint versions `0.x`

**Comment by tschaub** [comment]
As mentioned on https://github.com/adametry/gulp-eslint/pull/19#issuecomment-70566333, you can create [a simple `gulp` task](https://gist.github.com/tschaub/b7fed443597b979ceb28) that wraps the `eslint` CLI if you want to use the latest version.

**Pull request merged**
