### PR TITLE
Added failOnWarning and failAfterWarning

### PR DESCRIPTION
**Pull request by ericmatthys**
Similar to https://github.com/MoOx/eslint-loader, allow warnings to stop the task.

### CODE REVIEW

**Comment by shinnn** [comment]
Thanks, but looks weird API for me.

You can just set the rule values to `2` if you want the task to fail on validation. `failOnWarning` and `failAfterWarning` are inconsistent with the behavior of ESLint itself.

**Comment by ericmatthys** [comment]
Different environments might warrant different behavior. For example, an ESLint rule like `no-debugger` might be better as a warning during development, but when CI runs the tests, those issues should lead to a failure. Would you suggest that two separate ESLint configs be used in this situation? That seems like overkill to me.

**Comment by shinnn** [comment]
[`process.env`](https://nodejs.org/api/process.html#process_process_env) would help you.

```js
.pipe(eslint({
  rules: {
    'no-debugger': process.env.CI ? 2 : 1
  }
}))
```

**Comment by niedzielski** [comment]
This seems like a nice thing to have when transitioning old code to new rules and would model the behavior of the command line client when invoked with `--max-warnings 0`.

**Comment by niedzielski** [comment]
I just discovered [krmbkt/gulp-eslint-threshold]() which appears to cover this case.

**Pull request closed without merging**
