### PR TITLE
Update to latest ESLint version. Fixes Issue #111

### PR DESCRIPTION
**Pull request by scrapmac**
I am leaving the version field as is as I am not sure what new version should be provided

### CODE REVIEW

**Comment by scrapmac** [comment]
Hmmm, I think this is not required as it takes my installed eslint version itself.

**Comment by adametry** [comment]
**Here's why it works:**
When NPM installs, if a dependent installs a package that satisfies another package's dependency, the common package is installed only in the dependet's node_modules and it's shared by both.

In your case, your package.json includes installs eslint@1.7.3 (possibly). Since this meets gulp-eslint's dependency on eslint@^1.0.0 (effectively, @1.x.x), eslint is not installed within gulp-eslint's node_modules, and instead simply uses the installed sibling package.

This gives dependents the ability to set a specific eslint version, while ensuring that gulp-eslint has a compatible version of eslint. In an upcoming version of gulp-eslint, the eslint version dependency will change to "^1.4.0" to ensure that the "fix" option works. 

Thanks for the interest!

**Comment by scrapmac** [comment]
Yeah, figured that `^` stands for min version and after that, it reuses things if in same project. Still pretty new to npm.

**Comment by adametry** [comment]
It's a useful installation pattern of npm. If you want more detail on semver ranges, check out the [npm docs](https://docs.npmjs.com/misc/semver).

**Pull request closed without merging**
