### PR TITLE
Updated to eslint 0.19.0

### PR DESCRIPTION
**Pull request by doberkofler**

### CODE REVIEW

**Comment by shinnn** [comment]
@doberkofler Why did you closed this? Seems good PR. Would you mind updating [the expected error message of `fail.js`](https://github.com/adametry/gulp-eslint/blob/b83afbdc8508b5fa9aa5301df5d0aa0f6107aa31/test/fail.js#L21) to pass the test?

**Comment by doberkofler** [comment]
I was not able to run the tests locally and Travis CI failed so I decided to retract the pull request until I have sorted this out.

**Comment by shinnn** [comment]
> I was not able to run the tests locally

Interesting. I want to fix the problem.

* Could you show us the complete error log?
* Which OS?
* Node version?

**Comment by doberkofler** [comment]
node: 0.12.0
npm: 2.7.3

When trying to run `npm test`, I get the following:

```
D:\MyDev\doberkofler\gulp-eslint>npm test

> gulp-eslint@0.9.0 pretest D:\MyDev\doberkofler\gulp-eslint
> jscs *.js test/*.js && eslint *.js test/*.js

Error: Path *.js was not found.
    at D:\MyDev\doberkofler\gulp-eslint\node_modules\jscs\lib\checker.js:148:19
    at Array.<anonymous> (D:\MyDev\doberkofler\gulp-eslint\node_modules\jscs\node_modules\vow\lib\vow.js:699:56)
    at Immediate.callFns [as _onImmediate] (D:\MyDev\doberkofler\gulp-eslint\node_modules\jscs\node_modules\vow\lib\vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
npm ERR! Test failed.  See above for more details.
```

**Comment by shinnn** [comment]
Ah, OK. It seems that Windows doesn't resolve glob pattern `*.js` and directly try to find `*.js`, right?

Can you help me to fix this command to work on both POSIX and Windows environment?

```
jscs *.js test/*.js && eslint *.js test/*.js
```

**Comment by doberkofler** [comment]
I can think of 3 (relatively easy) ways to make this work:
* Using gulp itself to do the linting in it's own task (this is what I typically do)
* Using a `Makefile.js` and `shelljs` to implement the *.js pattern
* If you do not want to add any complexity, I can only think of specifying each file independently (`jscs index.js test/fail.js ...`)

**Pull request closed without merging**
