### PR TITLE
Support `fix` option

### PR DESCRIPTION
**Pull request by kui**
Add `gulpEslint.outputFixes` which write fixed contents to the files.

For example:

```javascript
gulp.src('js/**/*.js')
	.pipe(eslint({ fix: true })
	.pipe(eslint.outputFixes())
	.pipe(eslint.format())
```

### CODE REVIEW

**Comment by shinnn** [comment]
No tests.

**Comment by kui** [comment]
@shinnn 
Sorry about that. I added tests.

**Comment by adametry** [comment]
I appreciate the PR and tests; however, I'm not certain of the approach. Since gulp is basically streaming transformation tool, I believe it would be better to apply the fix to file.contents and use standard gulp.dest to write to disk.

I've recently published a release candidate that includes support for the "fix" option (among other things). This pre-release version can be installed using the "rc" tag, like so:

```shell
npm install gulp-eslint@rc
```

If you could, try it out and see if the following approach works for you:

```javascript
var gulp = require('gulp');
var eslint = require('gulp-eslint');
gulp.task('lint-fix', function () {
    return gulp.src('js/**/*.js')
        .pipe(eslint({ fix: true }))
        .pipe(eslint.format())
        .pipe(gulp.dest('./'));
});
```
Alternatively, here's a version that writes only writes files that eslint fixed, using `gulp-if`:
```javascript
var gulp = require('gulp');
var eslint = require('gulp-eslint');
var gulpIf = require('gulp-if');
function isFixed(file) {
    return file.eslint && typeof file.eslint.output === 'string';
}
gulp.task('lint-fix', function () {
    return gulp.src('js/**/*.js')
        .pipe(eslint({ fix: true }))
        .pipe(eslint.format())
        .pipe(gulpIf(isFixed, gulp.dest('./')));
});
```
By folding the fix to the gulp stream, it leaves the possibility for additional linting, transforms, concatenation, etc. Besides, with eslint able to "fix" source now, it's becoming a transformation tool (like a rule-based browserify-lite).

**Comment by kui** [comment]
@adametry 
I think it's the better way than my patch. I'll close this.
But I want your answer before @shinnn's [comment](https://github.com/adametry/gulp-eslint/pull/109#issuecomment-150104597) if possible. I misunderstood that this patch will be merged.
Thanks.

**Comment by scrapmac** [comment]
Hi, I am using the rc version like this: 

```javascript
function isFixed(file) {
  return file.eslint && typeof file.eslint.output === 'string';
}

gulp.task("lint", function() {
  return gulp.src("js/**/*.js")
    .pipe(eslint({
      fix: true,
      rules: {
        "no-multi-spaces": 2,
        "indent": [2, 2, {"SwitchCase": 1}]
      }
    }))
    .pipe(eslint.formatEach())
    .pipe(eslint.failAfterError())
    .pipe(gulpIf(isFixed, gulp.dest("./")));
});
```

When I run `gulp lint`, it does nothing - Neither does it fix the indentation or multiple spaces, nor does it output the errors on console. If I make `fix` as false, it reports the errors correctly. `failAfterError` has no effect.

**Comment by scrapmac** [comment]
And I found the issue - in `gulp.dest` you need to give the base directory. So in my case (and in the case of the example provided), it should be `gulp.dest("js")`

**Pull request closed without merging**
