### PR TITLE
Upgrade ESLint from v4 to v5

### PR DESCRIPTION
**Pull request by ehmicky**
This upgrades ESLint to the [next version](https://github.com/eslint/eslint/releases/tag/v5.0.0-alpha.0).

At the moment, only 5.0.0-alpha.0 is released, so I will update this pull request with newer versions until a stable version is released.

### CODE REVIEW

**Comment by ehmicky** [comment]
Upgraded to `5.0.0-alpha.1`.

**Comment by ehmicky** [comment]
Upgraded to `5.0.0-alpha.2`

**Comment by ehmicky** [comment]
Upgraded to `5.0.0-alpha.3`

**Comment by ehmicky** [comment]
Upgraded to `5.0.0-alpha.4`

**Comment by ehmicky** [comment]
Upgraded to `5.0.0-rc.0`

**Comment by shinnn** [comment]
@ehmicky Can you finish this up?

**Comment by gucong3000** [comment]
@shinnn We should fix CI fail first: #229

**Comment by ehmicky** [comment]
I was in summer vacation. Great this got merged!

**Pull request merged**
